when@dev:
    web_profiler:
        toolbar: true
        # Habilitar esta opción intercepta las redirecciones, por consecuencia
        # capturando los correos a enviar, en vez de utilizar una herramienta
        # como MailCatcher se puede utilizar esto para ver los contenidos del correo.
        intercept_redirects: true

    framework:
        profiler:
            only_exceptions: false
            collect_serializer_data: true

when@test:
    web_profiler:
        toolbar: false
        intercept_redirects: false

    framework:
        profiler: { collect: false }
