<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3yXjtgY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3yXjtgY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3yXjtgY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3yXjtgY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container3yXjtgY\App_KernelDevDebugContainer([
    'container.build_hash' => '3yXjtgY',
    'container.build_id' => '91898d5b',
    'container.build_time' => 1691685766,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3yXjtgY');
