<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAKLs4M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAKLs4M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPAKLs4M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPAKLs4M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPAKLs4M\App_KernelDevDebugContainer([
    'container.build_hash' => 'PAKLs4M',
    'container.build_id' => '6d92c21d',
    'container.build_time' => 1691508946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAKLs4M');
