<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA9v5rqi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA9v5rqi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA9v5rqi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA9v5rqi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA9v5rqi\App_KernelDevDebugContainer([
    'container.build_hash' => 'A9v5rqi',
    'container.build_id' => '044ce368',
    'container.build_time' => 1689624144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA9v5rqi');
